language: python
python: 3.6
git:
  depth: false
cache: 
  directories:
    - $HOME/.cache/pip
install:
  - pip install mkdocs==1.1.2 mkdocs-material==5.5.14
  - echo -e "machine github.com\n  login ${github_token}" > ~/.netrc
  - git checkout site && git checkout -qf $TRAVIS_COMMIT
script:
  - mkdocs gh-deploy --clean
